//category all
export const ListCategories = [
  { label: "Decorations", ThaiLable: "เครื่องประดับ" },
  { label: "Furniture", ThaiLable: "เฟอร์นิเจอร์" },
  { label: "Tools", ThaiLable: "เครื่องมือช่าง" },
  { label: "Fashion", ThaiLable: "เสื้อผ้าและแฟชั่น" },
  { label: "Sports", ThaiLable: "อุปกรณ์กีฬา" },
  { label: "Cosmetics", ThaiLable: "เครื่องสำอางค์" },
  { label: "Electrical", ThaiLable: "เครื่องใช้ไฟฟ้า" },
  { label: "Electronic", ThaiLable: "อุปกรณ์อิเล็กทรอนิกส์" },
  { label: "Baby", ThaiLable: "อุปกรณ์สำหรับเด็ก" },
  { label: "Health", ThaiLable: "สุขภาพและความงาม" },
  { label: "Office", ThaiLable: "อุปกรณ์เสริมสำหรับทำงาน" },
  { label: "Picture", ThaiLable: "ตกเเต่งบ้านหมวดรูปภาพ" },
  { label: "Kitchen", ThaiLable: "ห้องครัว" },
  { label: "Kitchen_accessories", ThaiLable: "อุปกรณ์เสริมห้องครัว" },
  { label: "Bathroom", ThaiLable: "อุปกรณ์ในห้องน้ำ" },
  { label: "Safety", ThaiLable: "อุปกรณ์ในด้านความปลอดภัย" },
  { label: "Snacks", ThaiLable: "อาหารทานเล่น" },
  { label: "Miscellaneous_Items", ThaiLable: "เบ็ดเตล็ด" },
  //เพิ่มประเภทของสิ้นค่า
];

export const ListProducts = {
  Decorations: [
    { label: "สร้อยคอ(Necklace)" },
    { label: "ต่างหู(Earrings)" },
    { label: "สร้อยข้อมือ(Bracelet)" },
    { label: "แหวน(Ring) " },
    { label: "สร้อยข้อเท้า(Anklet)" },
    { label: "พวงกุญแจ(Brooch)" },
    { label: "มงกุฎ(Tiara)" },
    { label: "นาฬิกาข้อมือ(Watch)" },
    { label: "แหวนที่ใส่บนจมูก(Nose Ring)" },
    { label: "เครื่องประดับที่มีหินรางหรืออัญมณี(Amuletic Jewelry)" },
  ],
  Furniture: [
    { label: "โซฟา(Sofa)" },
    { label: "เตียง(Bed)" },
    { label: "โต๊ะทานอาหาร(Dining Table)" },
    { label: "ตู้เสื้อผ้า(Wardrobe)" },
    { label: "ชั้นวางหนังสือ(Bookshelf)" },
    { label: "โต๊ะกาแฟ(Coffee Table)" },
    { label: "กระจก(Mirror)" },
    { label: "โคมไฟ(Lamp)" },
    { label: "หมอน(Cushions)" },
    { label: "เก้าอี้บาร์(Bar Stools)" },
    { label: "วอลเปเปอร์(Wallpaper)" },
  ],
  Tools: [
    { label: "สว่าน(Drill)" },
    { label: "กรรไกร(Scissors)" },
    { label: "ค้อน(Hammer)" },
    { label: "กาว(Glue)" },
    { label: "คีม(Chalk Line)" },
    { label: "ท่อน้ำ(Pipe)" },
    { label: "ถังใส่น้ำ(Water Bucket)" },
    { label: "แปรงทาสี(Paint Brush)" },
    { label: "ค้อนยิงตะปู(Nail Gun)" },
    { label: "แว่นป้องกันแสง(Safety Goggles)" },
  ],
  Fashion: [
    { label: "เสื้อและเสื้อยืด(Shirt and T-shirt)" },
    { label: "กางเกง(Pants)" },
    { label: "กระโปรง(Skirt)" },
    { label: "เสื้อเชิ้ตและเชี้ตเรียบ(Blouse and Plain Shirt)" },
    { label: "เสื้อคลุม(Coat)" },
    { label: "รองเท้า(Shoes)" },
    { label: "กระเป๋า(Bag)" },
    { label: "ชุดเดรส(Dress)" },
    { label: "แว่นตา(Eyeglasses) " },
    { label: "ชุดชั้นใน(Underwear)" },
    { label: "ชุดกีฬา(Sportswear) " },
    { label: "เจ็กเก็ต(Jacket)" },
  ],
  Sports: [
    { label: "ลูกบอล(Soccer Ball)" },
    { label: "ลูกบาสเกตบอล(Basket ball) " },
    { label: "ไม้กอล์ฟ(Golf Club)" },
    { label: "ไม้เบสบอล(Baseball Bat)" },
    { label: "ลูกวอลเลย์บอล(Hockey Stick)" },
    { label: "ไม้ปิงปอง(Ping Pong Paddle) " },
    { label: "จักรยาน(Bicycle)" },
    { label: "หมวกกันน็อค(Helmet)" },
    { label: "แว่นตาว่ายน้ำ(Goggles)" },
    { label: "ถุงมือมวย(Boxing Gloves)" },
  ],
  Cosmetics: [
    { label: "ลิปสติก(Lipstick)" },
    { label: "น้ำยาล้างเครื่องสำอาง(Makeup Remover)" },
    { label: "แปรงเครื่องสำอาง(Makeup Brushes)" },
    { label: "สีทาเล็บ(Nail Polish)" },
    { label: "ดินสอเขียนคิ้ว(Eyebrow Pencil)" },
    { label: "ขนตาปลอม(False Eyelashes)" },
    { label: "คอนซีลเลอร์(Concealer)" },
    { label: "บลัชออน(Blush)" },
    { label: "มาสคาร่า(Mascara)" },
    { label: "อายแชโดว์(Eyeshadow)" },
    { label: "อุปกรณ์กดสิวหัวดำ(Blackhead Remover)" },
  ],
  Electrical: [
    { label: "โทรทัศน์(Television)" },
    { label: "กล่องรับสัญญาณ(TrueID Box)" },
    { label: "ตู้เย็น(Refrigerator)" },
    { label: "เครื่องซักผ้า(Washing Machine)" },
    { label: "เครื่องปรับอากาศ(Air Conditioner)" },
    { label: "เครื่องอบไมโครเวฟ(Microwave)" },
    { label: "เครื่องปิ้งขนมปัง(Toaste)" },
    { label: "เครื่องปั่นผสมอาหาร(Blender)" },
    { label: "เครื่องดูดฝุ่น(Vacuum Cleaner)" },
    { label: "เครื่องเป่าผม(Hair Dryer)" },
    { label: "พัดลม(Fan)" },
  ],
  Electronic: [
    { label: "หูฟัง(Headphones)" },
    { label: "หูฟังไร้สาย(Wireless Earbuds)" },
    { label: "ลำโพง(Speaker)" },
    { label: "เราเตอร์(Router)" },
    { label: "เครื่องสแกนเนอร์(Scanner)" },
    { label: "กล้องดิจิตอล(Digital Camera)" },
    { label: "ลำโพงสมาร์ท(Smart Speaker)" },
    { label: "คอมพิวเตอร์ตั้งโต๊ะ(Desktop Computer)" },
    { label: "โทรศัพท์มือถือ(Mobile phone)" },
    { label: "คอมพิวเตอร์ขนาดพกพา(Portable computer)" },
    { label: "เครื่องพิมพ์เอกสารเเละหมึก(Pinter,Inktoker)" },
    { label: "จอมอนิเตอร์(Monitor)" },
    { label: "ไวไฟพกพา(Pocket Wifi)" },
    { label: "ตัวขยายสัญญาณไวไฟ(Range Extender)" },
    { label: "หน่วยความจำ(Ram)" },
  ],
  Baby: [
    { label: "เตียงเด็ก(Crib)" },
    { label: "อ่างอาบน้ำเด็ก(Baby Bath Tub)" },
    { label: "ผ้าอ้อม(Diapers)" },
    { label: "ขวดนมเด็ก(Baby Bottles)" },
    { label: "ของเล่นเด็ก(Baby Toys)" },
    { label: "เสื้อผ้าเด็ก(Baby Clothes)" },
    { label: "เบาะนั่งรถยนต์สำหรับเด็ก(Car Seat)" },
    { label: "เเชมพูเเละสบู่เหลวอาบน้ำเด็ก(Baby Shampoo and Soap)" },
    { label: "นม(Pacifier)" },
    { label: "ผ้าห่มเด็ก(Baby Blanket)" },
  ],
  Health: [
    { label: "แชมพู(Shampoo)" },
    { label: "วิตามิน(Multivitamins)" },
    { label: "น้ำมันตับปลา(Fish oil)" },
    { label: "ผลิตภัณฑ์สมุนไพรเสริมสุขภาพ(Herbalsupplements)" },
    { label: "เครื่องนวด(Body mist) " },
    { label: "น้ำมันผม(Hair oil)" },
    { label: "เเซรั่มบำรุงผม(Hair serum) " },
    { label: "มาส์กผม(Hair mask) " },
    { label: "น้ำมันหอมระเหย(Essential oils)" },
    { label: "การนวดข้อศอก,เเขน,ข้อเท้า,หัวเข่า(Elbow,Knee)" },
  ],
  Office: [
    { label: "ดินสอเขียน(Pencils)" },
    { label: "ปากกาลูกลื่น(Ballpoint pens)" },
    { label: "คริปหนีบกระดาษ(Paper clips)" },
    { label: "เมาส์เเละแผ่นรองเมาส์(Mouse,Mouse mat)" },
    { label: "ตัวจับกระดาษ(Document cabinets)" },
    { label: "คลิปสายไฟ(Cable clips)" },
    { label: "พื้นรองคีย์บอร์ด(Battery charging kits)" },
    { label: "การ์ดหน่วยความจำ(Memory cards)" },
    { label: "เครื่องคำนวณ(Calculators)" },
    { label: "เเฟลตไดร์(Flashdrive)" },
  ],
  Picture: [
    { label: "ภาพวาดสีน้ำ(Watercolor paintings)" },
    { label: "ภาพวาดน้ำมัน(Oil paintings)" },
    { label: "ผ้าม่านตกเเต่ง(Murals)" },
    { label: "พรม(Wall Art)" },
    { label: "ป้ายบอร์ด(Chalkboards)" },
    { label: "คอลเลคชั่นเทป(Collage tapes)" },
    { label: "อิลลัสเตรชัน(Sculptures)" },
    { label: "ภาพวาดการ์ตูน(Cartoon drawings)" },
    { label: "วอลเปเปอร์ (Wallpaper)" },
    { label: "กรอบรูป(Photo frames)" },
    { label: "สติกเกอร์ตกเเต่งผนัง(Wall stickers)" },
  ],
  Kitchen: [
    { label: "หม้อ(Pots)" },
    { label: "กระทะ(Pans)" },
    { label: "กาน้ำชา(Kettle)" },
    { label: "เครื่องปั่นและบดอาหาร(Blenders)" },
    { label: "ที่ปอกผักเเละผลไม้(Kitchen shears)" },
    { label: "ส้อม(Forks)" },
    { label: "มีด(Knives)" },
    { label: "เตาไฟฟ้า(Electric stove)" },
    { label: "เครื่องทำน้ำแข็ง(Ice makers)" },
  ],
  Kitchen_accessories: [
    { label: "เครื่องล้างจาน(Dishwasher)" },
    { label: "เครื่องล้างเเก้ว(Dishwashing glass)" },
    { label: "ขวดสำหรับใส่น้ำยาต่างๆ(Bottle)" },
    { label: "ฟองน้ำ(Sponge)" },
    { label: "กระติกน้ำ(Flask)" },
    { label: "ตะกร้าเก็บผักผลไม้(Basket)" },
    { label: "ถาดรองผักผลไม้(Tray)" },
    { label: "เตาอบ(Oven)" },
    { label: "ถังขยะ(Bin)" },
    { label: "เครื่องทำน้ำร้อน(Water heater)" },
    { label: "กล่องใส่อาหาร(Food Container)" },
  ],
  Bathroom: [
    { label: "มู่ลี่(Chick)" },
    { label: "กระเบื้องเซรามิก(Ceramic tile)" },
    { label: "ราวแขวนผ้า(Clothes rail)" },
    { label: "อ่างล้างหน้า(Basin)" },
    { label: "อ่างอาบน้ำ(Bath)" },
    { label: "ฟักบัว(Hatching)" },
    { label: "หลอดไฟ(Light bulb)" },
    { label: "กระเบื้องกระจก(Glass tile)" },
    { label: "พื้นไม้(Wooden floor)" },
    { label: "พัดลมระบายอากาศ(Ventilation fan)" },
  ],
  Safety: [
    { label: "ไฟฉาย(torch)" },
    { label: "กล้องวงจรปิด(closed-circuit camera)" },
    { label: "กล้อง IP(Internet Protocol)" },
    { label: "เสาตั้งกล้อง(camera pole)" },
    { label: "สายสัญญาณ(signal cable)" },
    { label: "แบตเตอรี่สำรอง(Backup Battery)" },
    { label: "สวิตช์(switch)" },
    { label: "สายเคเบิล(cable)" },
    { label: "กล่องหุ้มกล้อง(Camera Housing)" },
    { label: "อุปกรณ์ที่ใช้บันทึกภาพและวิดีโอจากกล้องวงจรปิด(DVR)" },
    { label: "ไมโครซอฟต่างๆ(Microsoft office,window10)" },
  ],
  Snacks: [
    { label: "มันฝรั่งแผ่น(Potato Chips)" },
    { label: "กล้องวงจรปิด(closed-circuit camera)" },
    { label: "ป๊อบคอร์น(Popcorn)" },
    { label: "เบเกิล(Pretzels)" },
    { label: "ธัญพืขรวม(Trail Mix)" },
    { label: "ขนมปังประเภทต่างๆ(Bread)" },
    { label: "ถั่ว(Nuts)" },
    { label: "ผลไม้เเช่แข็ง(Sliced Fruit)" },
    { label: "โยเกิร์ต(Yogurt)" },
    { label: "ลูกอม(Candy)" },
    { label: "เค้ก(Cake)" },
    { label: "กาแฟ(coffee)" },
  ],
  Miscellaneous_Items: [
    { label: "ฟิล์มกระจกนิรภัย(Safety Glass Film)" },
    { label: "สายสะพายกระเป๋า(Shoulder Strap)" },
    { label: "ตู้เกมหยอดเหรียญ(Coinoperatedgame)" },
    { label: "เหรียญ (coins)" },
    { label: "คัตเตอร์(Cutter)" },
    { label: "ตุ๊กตา(Doll)" },
    { label: "ถุงมือ(Gloves) " },
    {
      label:
        "สายเคเบิลและUSBต่างๆ(Lan Cable,Power cord,TypeC Cable,MicroUSB Cable)",
    },
    { label: "สายชาร์จ(Lightning Cable)" },
    { label: "หน้ากากอนามัย(Mask)" },
    { label: "เคสเเละฟิล์มมือถือ,เเท็บเล็ต(Case,Film)" },
  ],
};
