export const Descriptionstores = [
  { label: "ร้านสะดวกซื้อ (Convenience Store)" },
  { label: "ร้านขายอาหารจานด่วน (Fast Food Restaurant)" },
  { label: "ร้านอาหารไทย (Thai Restaurant)" },
  { label: "ร้านอาหารญี่ปุ่น (Japanese Restaurant)" },
  { label: "ร้านเสริมสวย (Beauty Salon)" },
  { label: "ร้านรองเท้า (Shoe Store)" },
  { label: "ร้านเสื้อผ้า (Clothing Store)" },
  { label: "ร้านเครื่องเสียง (Electronics Store)" },
  { label: "ร้านคอมพิวเตอร์ (Computer Store)" },
  { label: "ร้านอุปกรณ์กีฬา (Sports Equipment Store)" },
  { label: "ร้านอาหารเช้า (Breakfast Restaurant)" },
  { label: "ร้านอาหารใต้ (Southern Food Restaurant)" },
  { label: "ร้านอาหารอีสาน (Northeastern Food Restaurant)" },
  { label: "ร้านขายหนังสือ (Bookstore)" },
  { label: "ร้านรถยนต์ (Car Dealership)" },
  { label: "ร้านรองเท้ากีฬา (Athletic Shoe Store)" },
  { label: "ร้านเสื้อผ้าชาย (Men's Clothing Store)" },
  { label: "ร้านเสื้อผ้าหญิง (Women's Clothing Store)" },
  { label: "ร้านอุปกรณ์เดินป่า (Outdoor Gear Store)" },
  { label: "ร้านสมาชิกการกีฬา (Sports Club)" },
  { label: "ร้านอาหารจีน (Chinese Restaurant)" },
  { label: "ร้านอาหารอิตาเลียน (Italian Restaurant)" },
  { label: "ร้านอาหารเม็กซิกัน (Mexican Restaurant)" },
  { label: "ร้านสุขภาพและสปา (Health and Spa)" },
  { label: "ร้านเสื้อผ้าสไตล์วินเทจ (Vintage Clothing Store)" },
  { label: "ร้านเครื่องประดับ (Jewelry Store)" },
  { label: "ร้านรองเท้าแตะ (Flip-flop Store)" },
  { label: "ร้านของฝาก (Souvenir Shop)" },
  { label: "ร้านอาหารบุฟเฟต์ (Buffet Restaurant)" },
  { label: "ร้านอาหารไก่ทอด (Fried Chicken Restaurant)" },
  { label: "ร้านเครื่องดนตรี (Music Store)" },
  { label: "ร้านสัตว์เลี้ยง (Pet Store)" },
  { label: "ร้านเสื้อผ้าสปอร์ต (Sportswear Store)" },
  { label: "ร้านอาหารเวียดนาม (Vietnamese Restaurant)" },
  { label: "ร้านอาหารเหนือ (Northern Food Restaurant)" },
  { label: "ร้านรองเท้ารัดส้น (High Heel Shoe Store)" },
  { label: "ร้านเสื้อผ้าเด็ก (Children's Clothing Store)" },
  { label: "ร้านอาหารไอศกรีม (Ice Cream Shop)" },
  { label: "ร้านกาแฟ (Coffee Shop)" },
  { label: "ร้านอาหารฝรั่งเศส (French Restaurant)" },
  { label: "ร้านอาหารกรีก (Greek Restaurant)" },
  { label: "ร้านอาหารอินเดีย (Indian Restaurant)" },
  { label: "ร้านอาหารทะเล (Seafood Restaurant)" },
  { label: "ร้านเสื้อผ้ามุสลิม (Islamic Clothing Store)" },
  { label: "ร้านเครื่องสำอาง (Cosmetics Store)" },
  { label: "ร้านสตูดิโอฟิตเนส (Fitness Studio)" },
  { label: "ร้านบาร์เบอร์ (Barber Shop)" },
  { label: "ร้านอาหารไข่มุก (Bubble Tea Shop)" },
  { label: "ร้านอาหารเกาหลี (Korean Restaurant)" },
  { label: "ร้านอาหารบุฟเฟต์ญี่ปุ่น (Japanese Buffet)" },
  { label: "ร้านอาหารจากประเทศอื่นๆ (International Cuisine Restaurant)" },
  { label: "ร้านขายของสำหรับผู้หญิง (Women's Accessories Store)" },
  { label: "ร้านเสื้อผ้าสุนัข (Pet Clothing Store)" },
  { label: "ร้านอาหารอิสราเอล (Israeli Restaurant)" },
  { label: "ร้านอาหารเหนืออิตาลี (Northern Italian Restaurant)" },
  { label: "ร้านอาหารเวียดนาม (Vietnamese Restaurant)" },
  { label: "ร้านขายอุปกรณ์ตกปลา (Fishing Equipment Store)" },
  { label: "ร้านอาหารบะหมี่ (Noodle Shop)" },
  { label: "ร้านอาหารบุฟเฟต์จีน (Chinese Buffet)" },
  { label: "ร้านรองเท้าลำลอง (Hiking Shoe Store)" },
  { label: "ร้านอาหารแนะนำ (Recommended Restaurant)" },
  { label: "ร้านอาหารในสวน (Garden Restaurant)" },
  { label: "ร้านอาหารแบบไบรท์ (Barbecue Restaurant)" },
  { label: "ร้านเครื่องดื่ม (Beverage Shop)" },
  { label: "ร้านเครื่องมือช่าง (Hardware Store)" },
  { label: "ร้านเสื้อผ้าสเกตช์ (Skate Shop)" },
  { label: "ร้านอาหารมุสลิม (Halal Restaurant)" },
  { label: "ร้านอาหารพม่า (Burmese Restaurant)" },
  { label: "ร้านอาหารตุรกี (Turkish Restaurant)" },
  { label: "ร้านอาหารพื้นบ้าน (Local Cuisine Restaurant)" },
  { label: "ร้านขายบัตรประชาชน (ID Card Shop)" },
  { label: "ร้านอาหารมังสวิรัติ (Mongolian Restaurant)" },
  { label: "ร้านอาหารเมืองหลวง (Capital City Restaurant)" },
  { label: "ร้านเสื้อผ้าว่ายน้ำ (Swimwear Store)" },
  { label: "ร้านอาหารสเต็ก (Steakhouse)" },
  { label: "ร้านเสื้อผ้าในสไตล์วินเทจ (Vintage Style Clothing Store)" },
  { label: "ร้านอาหารเหนือญี่ปุ่น (Northern Japanese Restaurant)" },
  { label: "ร้านเครื่องดื่มสมุนไพร (Herbal Drink Shop)" },
  { label: "ร้านอาหารไทย-จีน (Thai-Chinese Restaurant)" },
  //เพิ่มประเภทของประเภทร้าน
];
